=== isamplesorg/metadata/iSamplesSchemaBasicSMR.json
{
    "$id": "http://resource.isamples.org/schema",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "PhysicalSampleRecord",
    "type": "object",
    "additionalProperties": false,
    "description": "This is a data object that is a digital representation of a physical sample, and thus shares the same identifier as the physical object. It provides  descriptive properties for any iSamples physical sample, URI for the metadata record is same as URI for physical sample-- digital object is considered twin of physical object, a representation. IGSN is recommended. Must be a URI that can be dereferenced on the web.",
    "properties": {
        "label": {
            "type": "string",
            "description": "string that will identify the sample for human users"
        },
        "sampleidentifier": {
            "type": "string",
            "description": "unique identifier for the physical object, ideally a URI that is physically attached to the specimen object"
        },
        "description": {
            "description": "free text description of the physical sample. Include as much detail as will be useful for users to find the sample and understand its context.",
            "type": "string"
        },
        "hasContextCategory": {
            "description": "top level context, based on the kind of feature sampled, from the SampledFeature vocabulary.  Specific identification of the sampled feature of interest is done through the SamplingEvent/Feature of Interest property.",
            "items": {
                "type": "string",
                "enum": [
                    "Biological environment",
                    "Building",
                    "Earth Surface",
                    "Earth environment",
                    "Experiment setting",
                    "Human occupation site ",
                    "Laboratory environment",
                    "Lake, River, or Stream bed",
                    "Marine biome",
                    "Marine environment",
                    "Regolith, sediment or soil horizon",
                    "Rock Body",
                    "Rock sample",
                    "Solid Earth",
                    "Subaerial Surface Environment",
                    "Subaerial terrestrial environment",
                    "Subaqueous terrestrial enviornment",
                    "Subsurface fluid reservoir",
                    "Terrestrial water body",
                    "Water body",
                    "atmosphere",
                    "extraterrestrial environment ",
                    "lab environment",
                    "marine water body bottom"
                ]
            },
            "type": "array"
        },
        "hasMaterialCategory": {
            "description": "specify the kind of material that constitutes the sample",
            "items": {"type": "string"},
            "type": "array"
        },
        "hasSpecimenCategory": {
            "description": "specify the kind of object that the specimen is",
            "items": {"type": "string"},
            "type": "array"
        },
        "keywords": {
            "description": "free text categorization of sample to support discovery",
            "items": {"type": "string"},
            "type": "array"
        },
        "producedBy": {
            "$ref": "#/definitions/SamplingEvent",
            "description": "object that documents the sampling event--who, where, when the specimen was obtained"
        },
        "registrant": {
            "description": "identification of the agent that registered the sample, with contact information. Should include person name and affiliation, or position name and affiliation, or just organization name. e-mail address is preferred contact information.",
            "type": "string"
        },
        "samplingPurpose": {
            "description": "term to specify why a sample was collection.",
            "type": "string"
        }
    },
    "required": [
        "sampleidentifier",
        "label"
    ],
    "definitions": {
        "GeospatialDDCoordLocation": {
            "title": "GeospatialDDCoordLocation",
            "type": "object",
            "additionalProperties": true,
            "description": "specification of WGS84 decimal degree location of sampling location; could be sample point location, or the centroid of a sampling area",
            "properties": {
                "elevation": {
                    "description": "should be a number and Unit of measure, and the datum. e.g. 401 m above mean sea level.",
                    "type": "string"
                },
                "latitude": {
                    "description": "angular coordinate measured positive north from the equator.",
                    "type": "number",
                    "minimum": -90,
                    "maximum": 90
                },
                "longitude": {
                    "description": "angular coordinate measured positive eastward from the prime meridian.",
                    "type": "number",
                    "minimum": -360,
                    "maximum": 360
                }
            },
            "required": [
                "latitude",
                "longitude"
            ]
        },
        "SamplingEvent": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "label": {
                    "description": "a human intelligible string used to uniquely identify the sampling event.",
                    "type": "string"
                },
                "description": {
                    "description": "free text description of the sampling event",
                    "type": "string"
                },
                "hasFeatureOfInterest": {
                    "description": "what does the sample represent.",
                    "type": "string"
                },
                "responsibility": {
                    "description": "String with person name and affiliation, or organization name, and their role relative to the parent element.",
                    "items": {"type": "string"},
                    "type": "array"
                },
                "resultTime": {
                    "description": "Date on which the sample was collected.",
                    "type": "string"
                },
                "samplingSite": {
                    "$ref": "#/definitions/SamplingSite",
                    "description": "object that identifies the place where the sample was collected"
                }
            },
            "required": ["label"],
            "title": "SamplingEvent",
            "type": "object"
        },
        "SamplingSite": {
            "additionalProperties": false,
            "description": "documentation of the site where the sample was collected, wtih place name(s) and a geospatial location",
            "properties": {
                "description": {
                    "description": "free text description of the subject of a triple.",
                    "type": "string"
                },
                "label": {
                    "description": "a human intelligible string used to identify a thing, i.e. the name to use for the thing; should be unique in the scope of a sample collection or dataset.",
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/GeospatialDDCoordLocation",
                    "description": "geopatial location of site; required default is WGS84 latitude, longitude in decimal degrees. Elevation as a string with number, unit of measure, and datum."
                },
                "placeName": {
                    "description": "one or more names by which the sampling site is known.",
                    "items": {"type": "string"},
                    "type": "array"
                }
            },
            "required": ["label"],
            "title": "SamplingSite",
            "type": "object"
        }
    }
}

=== isamplesorg/metadata/examples/iSamples/iSamplesExRockSampleBasic.json
{
    "$schema": "iSamplesSchemaBasicSMR.json",
    "label": "smr2007-02-07 Blue Tank Granite",
    "sampleidentifier": "https://igsn.org/smr2096856",
    "description": "Sample of Blue Tank Granite collected in SW Harquahala Mountains; medium-grained biotite granitoid with distictive 1 mm honey-colored sphene crystals. Approx 15 by 15 by 15 cm.",
    "hasContextCategory": [ "Rock Body" ],
    "hasMaterialCategory": ["Rock"],
    "hasSpecimenCategory": ["Other solid object"],
    "keywords": [
        "granitoid",
        "Mesoproterozoic",
        "Harquahala Thrust Plate"
    ],
    "producedBy": {
        "label": "Sampling event",
        "description": "Field geologic sample taken from outcrop",
        "hasFeatureOfInterest": "Blue Tank Granite",
        "responsibility": ["Stephen M. Richard, geo@email.com, collector"],
        "resultTime": "2007-02-07",
        "samplingSite": {
            "description": "outcrop in wash bottom",
            "label": "outcrop",
            "location": {
                "elevation": "705 m above MSL",
                "latitude": 33.741,
                "longitude": -113.364
            },
            "placeName": [
                "Blue Tank Wash",
                "Harquahala Mountains",
                "Arizona",
                "La Paz County"
            ]
        }
    },
    "registrant": "Joe Samplecurator, joe@somewhere.net",
    "samplingPurpose": "representative lithology"
}
