=== isamplesorg/metadata/iSamplesSchemaBasic0.3.json
{
    "$id": "http://resource.isamples.org/schema/0.3",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "PhysicalSampleRecord",
    "description": "This is a data object that is a digital representation of a physical sample, and thus shares the same identifier as the physical object. It provides  descriptive properties for any iSamples physical sample, URI for the metadata record is same as URI for physical sample-- digital object is considered twin of physical object, a representation. IGSN is recommended. Must be a URI that can be dereferenced on the web. ",
    "type": "object",
    "required": [
        "sampleidentifier",
        "label"
    ],
    "additionalProperties": true,
    "properties": {
        "curation": {"$ref": "#/definitions/Curation"},
        "description": {
            "description": "free text description of the subject of a triple.",
            "type": "string"
        },
        "hasContextCategory": {
            "description": "top level context, based on the kind of feature sampled.  Specific identification of the sampled feature of interest is done through the SamplingEvent/Feature of Interest property.",
            "items": {"$ref": "#/definitions/Contextcategory"},
            "type": "array"
        },
        "hasMaterialCategory": {
            "description": "specify the kind of material that constitutes the sample",
            "items": {"$ref": "#/definitions/Materialtype"},
            "type": "array"
        },
        "hasSpecimenCategory": {
            "description": "specify the kind of object that the specimen is",
            "items": {"$ref": "#/definitions/Specimencategory"},
            "type": "array"
        },
        "id": {
            "description": "identifier for the JSON object. JSON-LD context should map this to @id",
            "type": "string"
        },
        "informalClassification": {
            "description": "free text classification terms, not from a controlled vocabulary; generally terms applied by collector",
            "items": {"type": "string"},
            "type": "array"
        },
        "keywords": {
            "description": "free text categorization of sample to support discovery",
            "items": {"type": "string"},
            "type": "array"
        },
        "label": {
            "description": "a human intelligible string used to identify a thing, i.e. the name to use for the thing; should be unique in the scope of a sample collection or dataset.",
            "type": "string"
        },
        "producedBy": {
            "description": "object that documents the sampling event--who, where, when the specimen was obtained",
            "$ref": "#/definitions/SamplingEvent"
        },
        "registrant": {
            "description": "identification of the agent that registered the sample, with contact information. Should include person name and affiliation, or position name and affiliation, or just organization name. e-mail address is preferred contact information.",
            "type": "string"
        },
        "relatedResource": {
            "description": "link to related resource with relationship property to indicate nature of connection. Target should be identifier for a resource.",
            "items": {"$ref": "#/definitions/SampleRelation"},
            "type": "array"
        },
        "sampleidentifier": {
            "description": "URI that identifies the physical sample described by this record",
            "type": "string"
        },
        "samplingPurpose": {
            "description": "term to specify why a sample was collection.",
            "type": "string"
        }
    },
    "definitions": {
        "Contextcategory": {
            "description": "top level context, based on the kind of feature sampled, from the SampledFeature vocabulary.  Specific identification of the sampled feature of interest is done through the SamplingEvent/Feature of Interest property.",
            "enum": [
                "Active human occupation site",
                "Atmosphere",
                "Earth interior",
                "Experiment setting",
                "Extraterrestrial environment",
                "Glacier environment",
                "Site of past human activities",
                "Laboratory environment",
                "Lake, river or stream bottom",
                "Marine biome",
                "Marine water body",
                "Marine water body bottom",
                "Subaerial surface environment",
                "Subaerial terrestrial biome",
                "Subaqueous terrestrial biome",
                "Subsurface fluid reservoir",
                "Terrestrial water body",
                "Not Provided"
            ],
            "title": "Contextcategory",
            "type": "string"
        },
        "Curation": {
            "additionalProperties": true,
            "description": "object contains information about current storage of sample, access to sample, and events in curation history. Curation as used here starts when the sample is removed from its original context, and might include various processing steps for preservation.  Processing related to analysis preparation such as crushing, dissolution, evaporation, filtering are considered part of the sampling method for the derived child sample.",
            "properties": {
                "accessConstraints": {
                    "description": "cultural, legal or other policy issues that bear on access to view, borrow, or subsample a sample or visit a sampling site.",
                    "type": "string"
                },
                "curationLocation": {
                    "description": "information about where the sample is currently stored",
                    "type": "string"
                },
                "description": {
                    "description": "free text description of the subject of a triple.",
                    "type": "string"
                },
                "label": {
                    "description": "a human intelligible string used to identify a thing, i.e. the name to use for the thing; should be unique in the scope of a sample collection or dataset.",
                    "type": "string"
                },
                "responsibility": {
                    "description": "String with person name and affiliation, or organization name, and their role relative to the parent element.",
                    "items": {"type": "string"},
                    "type": "array"
                }
            },
            "required": [],
            "title": "Curation",
            "type": "object"
        },
        "GeospatialDDCoordLocation": {
            "additionalProperties": true,
            "description": "Coordinate location specified using decimal degrees in WGS84 spatial reference system. Standard location specification is necessary for interoperability.",
            "properties": {
                "elevation": {
                    "description": "should be a number and Unit of measure, and the datum. e.g. 401 m above mean sea level.",
                    "type": "string"
                },
                "latitude": {
                    "description": "angular coordinate measured positive north from the equator.",
                    "type": "number"
                },
                "longitude": {
                    "description": "angular coordinate measured positive eastward from the prime meridian.",
                    "type": "number"
                }
            },
            "required": [
                "latitude",
                "longitude"
            ],
            "title": "GeospatialDDCoordLocation",
            "type": "object"
        },
        "Materialtype": {
            "description": "categories for kinds of material that constitute the sample",
            "enum": [
                "Anthropogenic material",
                "Anthropogenic metal",
                "Biogenic non-organic material",
                "Gaseous material",
                "Ice",
                "Mineral",
                "Non-aqueous liquid material",
                "Not Provided",
                "Organic material",
                "Particulate",
                "Rock",
                "Sediment",
                "Soil",
                "Water"
            ],
            "title": "Materialtype",
            "type": "string"
        },
        "SampleRelation": {
            "additionalProperties": true,
            "description": "Object specifying relationships to other samples, (particularly between subsamples and parent samples), or beteen samples and other related information, e.g. publications using data from the sample or providing background information to understand the sample.",
            "properties": {
                "description": {
                    "description": "free text description of the subject of a triple.",
                    "type": "string"
                },
                "label": {
                    "description": "a human intelligible string used to identify a thing, i.e. the name to use for the thing; should be unique in the scope of a sample collection or dataset.",
                    "type": "string"
                },
                "relationship": {
                    "description": "term to identify realationship between host sample and the sample relation target. Should be controlled vocabulary (ScopedName). for now start with string, 'derivedFrom'.",
                    "type": "string"
                },
                "target": {
                    "description": "identifier for the target resource in the relationship. Start with string, should be Identifier object.",
                    "type": "string"
                }
            },
            "required": [
                "relationship",
                "target"
            ],
            "title": "SampleRelation",
            "type": "object"
        },
        "SamplingEvent": {
            "additionalProperties": true,
            "description": "Object that describes the sample collection event, provides linkage to feature of interest, collection location and procedure, and the responsible parties, including people and projects supportign the collection activity.",
            "properties": {
                "description": {
                    "description": "free text description of the subject of a triple.",
                    "type": "string"
                },
                "hasFeatureOfInterest": {
                    "description": "what does the sample represent.",
                    "type": "string"
                },
                "id": {
                    "description": "identifier for the JSON object. JSON-LD context should map this to @id",
                    "type": "string"
                },
                "label": {
                    "description": "a human intelligible string used to identify a thing, i.e. the name to use for the thing; should be unique in the scope of a sample collection or dataset.",
                    "type": "string"
                },
                "responsibility": {
                    "description": "String with person name and affiliation, or organization name, and their role relative to the parent element.",
                    "items": {"type": "string"},
                    "type": "array"
                },
                "resultTime": {
                    "description": "Date on which the sample was collected.",
                    "type": "string"
                },
                "samplingSite": {
                    "$ref": "#/definitions/SamplingSite",
                    "description": "object that identifies the place where the sample was collected"
                }
            },
            "required": ["label"],
            "title": "SamplingEvent",
            "type": "object"
        },
        "SamplingSite": {
            "additionalProperties": true,
            "description": "Object providing location information for the site at which the sample was collected; this might be a place name, or a coordinate location in a global (e.g. WGS 84) or local (e.g. relative to a borehole or local excavation grid) reference system.",
            "properties": {
                "description": {
                    "description": "free text description of the subject of a triple.",
                    "type": "string"
                },
                "label": {
                    "description": "a human intelligible string used to identify a thing, i.e. the name to use for the thing; should be unique in the scope of a sample collection or dataset.",
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/GeospatialDDCoordLocation",
                    "description": "geopatial location of site; required default is WGS84 latitude, longitude in decimal degrees. Elevation as a string with number, unit of measure, and datum."
                },
                "placeName": {
                    "description": "one or more names by which the sampling site is known.",
                    "items": {"type": "string"},
                    "type": "array"
                }
            },
            "required": ["label"],
            "title": "SamplingSite",
            "type": "object"
        },
        "Specimencategory": {
            "description": "specify the kind of object that the specimen is",
            "enum": [
                "Aggregation",
                "Analytical preparation",
                "Anthropogenic aggregation",
                "Artifact",
                "Biome aggregation",
                "Experiment product",
                "Fossil",
                "Liquid or gas sample",
                "Organism part",
                "Organism product",
                "Other solid object",
                "Whole organism",
                "Not Provided"
            ],
            "title": "Specimencategory",
            "type": "string"
        }
    }
}

=== isamplesorg/metadata/examples/schemaTesting/0.3.2.instance1.json
{
    "curation": {
        "accessConstraints": "jzcvrfWY",
        "curationLocation": "STUjOicmbYId",
        "description": "XxpYjgydTYKAh",
        "label": "xxOBfsNIshcXlc",
        "responsibility": [
            "sSxzWuRGIjsUTb",
            "LNQ",
            "qCCZWhvck"
        ]
    },
    "description": "vPKzYQDDl",
    "hasContextCategory": [
        "Glacier environment",
        "Extraterrestrial environment",
        "Subaerial surface environment"
    ],
    "hasMaterialCategory": [
        "Biogenic non-organic material",
        "Not Provided",
        "Anthropogenic metal"
    ],
    "hasSpecimenCategory": [
        "Artifact",
        "Analytical preparation",
        "Not Provided"
    ],
    "id": "KHRyiYLOpLexm",
    "informalClassification": [
        "BYFDqA",
        "c",
        "Dx",
        "KMsPMdvb",
        "ETtGDhSNdMFqrEWkjWo",
        "OyHyWzS"
    ],
    "keywords": [
        "lt",
        "BtylVavJnDZy",
        "DMFeU"
    ],
    "label": "odFaiJnLhIWjmTNWasTZ",
    "producedBy": {
        "description": "QCAxCWrzREfVGVorCWFm",
        "hasFeatureOfInterest": "dQD",
        "id": "x",
        "label": "CEIMABpWfWiB",
        "responsibility": [
            "xkzVnJZbyZLBXSeXc",
            "nEgIjQUQ",
            "grMBoO",
            "qz",
            "tsSBuyH"
        ],
        "resultTime": "EqEB",
        "samplingSite": {
            "description": "rtPBuPQ",
            "label": "CjktuLhuQInbrm",
            "location": {
                "elevation": "EOUCZkkifBjjiXZTqr",
                "latitude": 41,
                "longitude": 7
            },
            "placeName": ["rNf"]
        }
    },
    "registrant": "UeNLPoow",
    "relatedResource": [
        {
            "description": "zQFGWaZRtrKy",
            "label": "KTENDHiiyeuBQNR",
            "relationship": "bDrEqJlElQfcGqhVpv",
            "target": "gnLHcVnvtKEbwnLeZuym"
        },
        {
            "description": "ugJlQKwAA",
            "label": "CULgCL",
            "relationship": "qu",
            "target": "wdocYwLv"
        },
        {
            "description": "innV",
            "label": "P",
            "relationship": "oAcvtVqTGwuClob",
            "target": "HGXurgCMOEPgSBnUj"
        }
    ],
    "sampleidentifier": "rQuCuzmdvOF",
    "samplingPurpose": "dYoBAlrnltbcib"
}
